// <auto-generated />
namespace Webpopytka_4_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class LastLoginTimeIsMadeNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LastLoginTimeIsMadeNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202108012019557_LastLoginTimeIsMadeNullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
